import { emptyTrajectory } from "./catalog";
import type { Member, TrajectoryStep, TrajectoryStepId } from "./types";

function steps(
  completed: TrajectoryStepId[],
  dates: Partial<Record<TrajectoryStepId, string>> = {}
): TrajectoryStep[] {
  const set = new Set(completed);
  return emptyTrajectory().map((step) => ({
    ...step,
    completed: set.has(step.id),
    completedAt: set.has(step.id) ? dates[step.id] ?? "2025-01-12" : undefined,
  }));
}

export const SEED_MEMBERS: Member[] = [
  {
    id: "m-jose-herrera",
    firstName: "José Luis",
    lastName: "Herrera",
    gender: "masculino",
    birthDate: "1978-03-14",
    phone: "555-210-4481",
    email: "jose.herrera@labendicion.org",
    address: "Calle Roble 21",
    city: "Ciudad Central",
    maritalStatus: "casado",
    occupation: "Administrador",
    howTheyCame: "familia",
    conversionDate: "1999-06-20",
    status: "activo",
    ministries: [
      { ministryId: "diaconado", role: "lider" },
      { ministryId: "caballeros", role: "lider" },
    ],
    trajectory: steps(
      [
        "visitante",
        "nuevo_creyente",
        "discipulado",
        "bautismo",
        "membresia",
        "servicio",
        "liderazgo",
      ],
      {
        visitante: "1999-04-11",
        nuevo_creyente: "1999-06-20",
        discipulado: "1999-09-05",
        bautismo: "1999-10-31",
        membresia: "2000-01-16",
        servicio: "2001-03-04",
        liderazgo: "2012-08-19",
      }
    ),
    notes: "Coordina el diaconado y acompaña a las familias nuevas.",
    createdAt: "2020-01-10T10:00:00.000Z",
    updatedAt: "2026-08-12T10:00:00.000Z",
  },
  {
    id: "m-maria-vargas",
    firstName: "María Elena",
    lastName: "Vargas",
    gender: "femenino",
    birthDate: "1986-11-02",
    phone: "555-318-7720",
    email: "maria.vargas@correo.com",
    address: "Av. del Lago 450",
    city: "Ciudad Central",
    maritalStatus: "casado",
    occupation: "Maestra",
    howTheyCame: "invitacion",
    invitedBy: "Rosa Torres",
    conversionDate: "2016-05-08",
    status: "activo",
    ministries: [
      { ministryId: "alabanza", role: "lider" },
      { ministryId: "damas", role: "servidor" },
    ],
    trajectory: steps(
      [
        "visitante",
        "nuevo_creyente",
        "discipulado",
        "bautismo",
        "membresia",
        "servicio",
      ],
      {
        visitante: "2016-03-20",
        nuevo_creyente: "2016-05-08",
        discipulado: "2016-07-17",
        bautismo: "2016-09-25",
        membresia: "2017-01-08",
        servicio: "2017-04-02",
      }
    ),
    notes: "Dirige el ensayo de alabanza los jueves por la noche.",
    createdAt: "2016-03-20T15:00:00.000Z",
    updatedAt: "2026-07-30T15:00:00.000Z",
  },
  {
    id: "m-ana-mendoza",
    firstName: "Ana Sofía",
    lastName: "Mendoza",
    gender: "femenino",
    birthDate: "2003-07-21",
    phone: "555-401-2298",
    email: "anasofia.mendoza@correo.com",
    city: "Ciudad Central",
    maritalStatus: "soltero",
    occupation: "Estudiante de enfermería",
    howTheyCame: "redes",
    conversionDate: "2024-11-03",
    status: "activo",
    ministries: [{ ministryId: "jovenes", role: "servidor" }],
    trajectory: steps(
      ["visitante", "nuevo_creyente", "discipulado", "bautismo"],
      {
        visitante: "2024-09-15",
        nuevo_creyente: "2024-11-03",
        discipulado: "2025-01-19",
        bautismo: "2025-04-20",
      }
    ),
    notes: "Está en el grupo de discipulado de jóvenes. Lista para membresía.",
    createdAt: "2024-09-15T18:00:00.000Z",
    updatedAt: "2026-04-20T18:00:00.000Z",
  },
  {
    id: "m-lucia-castro",
    firstName: "Lucía Fernanda",
    lastName: "Castro",
    gender: "femenino",
    birthDate: "1992-01-30",
    phone: "555-612-8844",
    email: "lucia.castro@correo.com",
    address: "Pasaje Las Palmas 8",
    city: "Villa Norte",
    maritalStatus: "casado",
    occupation: "Diseñadora gráfica",
    howTheyCame: "evento",
    conversionDate: "2019-08-11",
    status: "activo",
    ministries: [
      { ministryId: "ninos", role: "lider" },
      { ministryId: "multimedia", role: "apoyo" },
    ],
    trajectory: steps(
      [
        "visitante",
        "nuevo_creyente",
        "discipulado",
        "bautismo",
        "membresia",
        "servicio",
      ],
      {
        visitante: "2019-06-02",
        nuevo_creyente: "2019-08-11",
        discipulado: "2019-10-06",
        bautismo: "2019-12-15",
        membresia: "2020-02-09",
        servicio: "2020-06-21",
      }
    ),
    notes: "Coordina la escuela bíblica infantil los domingos.",
    createdAt: "2019-06-02T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z",
  },
  {
    id: "m-rosa-torres",
    firstName: "Rosa Isabel",
    lastName: "Torres",
    gender: "femenino",
    birthDate: "1969-09-09",
    phone: "555-733-1090",
    city: "Ciudad Central",
    maritalStatus: "viudo",
    occupation: "Ama de casa",
    howTheyCame: "familia",
    conversionDate: "2008-02-17",
    status: "activo",
    ministries: [{ ministryId: "intercesion", role: "lider" }],
    trajectory: steps(
      [
        "visitante",
        "nuevo_creyente",
        "discipulado",
        "bautismo",
        "membresia",
        "servicio",
        "liderazgo",
      ],
      {
        visitante: "2007-11-04",
        nuevo_creyente: "2008-02-17",
        discipulado: "2008-05-11",
        bautismo: "2008-07-27",
        membresia: "2008-10-12",
        servicio: "2009-03-01",
        liderazgo: "2018-05-06",
      }
    ),
    notes: "Lidera el círculo de oración de los martes a las 6:00 a. m.",
    createdAt: "2007-11-04T08:00:00.000Z",
    updatedAt: "2026-05-06T08:00:00.000Z",
  },
  {
    id: "m-daniel-morales",
    firstName: "Daniel Felipe",
    lastName: "Morales",
    gender: "masculino",
    birthDate: "1998-04-18",
    phone: "555-880-4412",
    email: "daniel.morales@correo.com",
    city: "Ciudad Central",
    maritalStatus: "soltero",
    occupation: "Técnico en sistemas",
    howTheyCame: "invitacion",
    invitedBy: "José Luis Herrera",
    conversionDate: "2023-03-12",
    status: "activo",
    ministries: [{ ministryId: "multimedia", role: "servidor" }],
    trajectory: steps(
      [
        "visitante",
        "nuevo_creyente",
        "discipulado",
        "bautismo",
        "membresia",
        "servicio",
      ],
      {
        visitante: "2023-01-08",
        nuevo_creyente: "2023-03-12",
        discipulado: "2023-05-21",
        bautismo: "2023-08-06",
        membresia: "2023-10-15",
        servicio: "2024-02-04",
      }
    ),
    notes: "Opera audio y transmisión en los cultos de domingo.",
    createdAt: "2023-01-08T17:00:00.000Z",
    updatedAt: "2026-02-04T17:00:00.000Z",
  },
  {
    id: "m-carlos-ruiz",
    firstName: "Carlos Andrés",
    lastName: "Ruiz",
    gender: "masculino",
    birthDate: "1995-12-05",
    phone: "555-902-6711",
    email: "carlos.ruiz@correo.com",
    city: "Villa Norte",
    maritalStatus: "soltero",
    occupation: "Chofer",
    howTheyCame: "invitacion",
    invitedBy: "Daniel Felipe Morales",
    conversionDate: "2026-08-17",
    status: "nuevo_creyente",
    ministries: [],
    trajectory: steps(["visitante", "nuevo_creyente"], {
      visitante: "2026-08-10",
      nuevo_creyente: "2026-08-17",
    }),
    notes: "Recién entregó su vida a Cristo. Asignar discipulador esta semana.",
    createdAt: "2026-08-10T19:30:00.000Z",
    updatedAt: "2026-08-17T19:30:00.000Z",
  },
  {
    id: "m-pedro-gomez",
    firstName: "Pedro Antonio",
    lastName: "Gómez",
    gender: "masculino",
    birthDate: "1981-06-28",
    phone: "555-244-0193",
    city: "Ciudad Central",
    maritalStatus: "casado",
    occupation: "Comerciante",
    howTheyCame: "evento",
    status: "visitante",
    ministries: [],
    trajectory: steps(["visitante"], { visitante: "2026-08-24" }),
    notes: "Vino con su esposa al culto del domingo. Quiere volver el próximo.",
    createdAt: "2026-08-24T20:00:00.000Z",
    updatedAt: "2026-08-24T20:00:00.000Z",
  },
];
